generator/templates/blink/Object.h, generator/templates/blink/Objects.cpp, src/include/nxt/EnumClassBitmasks.h
PTAL, these changes are needed to compile with ToT Chromium.
=> Chrome update

generator/main.py
=> Add shebang to generator/main.py to use python2

generator/templates/wire/WireClient.cpp, generator/templates/wire/WireServer.cpp
These are apparently required for me to build on my Linux machine.
=> Fix Linux build

CMakeLists.txt, examples/Animometer.cpp, examples/CMakeLists.txt, examples/ComputeBoids.cpp, examples/HelloCompute.cpp, examples/HelloIndices.cpp, examples/HelloInstancing.cpp, examples/HelloTriangle.c, examples/HelloTriangle.cpp, examples/HelloUBO.cpp, examples/HelloVertices.cpp, examples/RenderToTexture.cpp, examples/Utils.cpp, examples/Utils.h, examples/glTFViewer/glTFViewer.cpp, generator/CMakeLists.txt, generator/main.py, generator/templates/mock_api.h, src/backend/CMakeLists.txt, src/backend/common/CommandAllocator.cpp, src/backend/common/Math.cpp, src/backend/common/Math.h, src/tests/unittests/MathTests.cpp, src/tests/unittests/RefCountedTests.cpp, src/wire/CMakeLists.txt, third_party/CMakeLists.txt
This fixes Windows compilation locally. @kainino0x PTAL too! There are still a bunch of warnings on Windows that we should remove incrementally.
This still misses one fix for nxtcpp.h's ObjectBase that will be in the validation test PR.
=> Windows compilation

.travis.yml, examples/glTFViewer/glTFViewer.cpp, generator/CMakeLists.txt, generator/main.py, src/backend/common/BitSetIterator.h, src/backend/common/Math.cpp, src/wire/CMakeLists.txt, src/wire/TerribleCommandBuffer.cpp, src/wire/TerribleCommandBuffer.h
PTAL @kainino0x, @austinEng. This adds continuous integration testing of compilation and nxt_unittests on [Linux, OSX] x [Clang, GCC] x [Debug, Release]. I will take a look at AppVeyor for Windows CI next.
=> Add Travis CI

.appveyor.yml
PTAL @kainino0x @austinEng 
AppVeyor support was mostly painless but I only put it on one configuration. Ideally we will extend it to test in Release, other versions of VS and maybe different archs.
=> Add AppVeyor CI

examples/HelloDepthStencil.cpp, examples/Utils.cpp, examples/Utils.h, src/backend/common/DepthStencilState.cpp, src/backend/opengl/CommandBufferGL.cpp, src/backend/opengl/DepthStencilStateGL.cpp, src/backend/opengl/PersistentPipelineStateGL.cpp, src/backend/opengl/PersistentPipelineStateGL.h
=> Fix some nits from depth-stencil PR

examples/glTFViewer/glTFViewer.cpp
=> Update glTFViewer for render passes and depth stencil state

src/backend/common/CommandBuffer.cpp, src/backend/common/CommandBufferStateTracker.cpp, src/backend/common/CommandBufferStateTracker.h, src/backend/common/Framebuffer.cpp, src/tests/CMakeLists.txt, src/tests/unittests/validation/CommandBufferValidationTests.cpp, src/tests/unittests/validation/FramebufferValidationTests.cpp, src/tests/unittests/validation/RenderPassValidationTests.cpp
=> Add validation for some null arguments and dangling render passes

src/backend/CMakeLists.txt, src/backend/common/SerialQueue.h, src/tests/CMakeLists.txt, src/tests/unittests/SerialQueueTests.cpp
=> Introduce SerialQueue to track in flight resources

next.json, src/backend/common/InputState.cpp, src/backend/d3d12/InputStateD3D12.cpp, src/backend/metal/CommandBufferMTL.mm, src/backend/metal/InputStateMTL.mm, src/backend/metal/PipelineMTL.mm, src/backend/metal/TextureMTL.mm, src/backend/opengl/CommandBufferGL.cpp, src/tests/CMakeLists.txt, src/tests/NXTTest.cpp, src/tests/NXTTest.h, src/tests/end2end/BasicTests.cpp, src/tests/end2end/InputStateTests.cpp, src/tests/unittests/validation/InputStateValidationTests.cpp, src/utils/NXTHelpers.cpp, src/utils/NXTHelpers.h
PTAL, this contain the first end2end tests actually rendering something.
=> Input state tests

generator/templates/wire/WireServer.cpp, src/backend/common/Pipeline.cpp, src/backend/common/Pipeline.h, src/backend/metal/CommandBufferMTL.h, src/backend/metal/CommandBufferMTL.mm, src/backend/metal/MetalBackend.h, src/backend/metal/MetalBackend.mm, src/backend/opengl/CommandBufferGL.cpp, src/backend/opengl/CommandBufferGL.h, src/backend/opengl/DepthStencilStateGL.cpp, src/backend/opengl/DepthStencilStateGL.h, src/backend/opengl/OpenGLBackend.cpp, src/backend/opengl/OpenGLBackend.h, src/backend/opengl/PipelineGL.cpp, src/backend/opengl/PipelineGL.h, src/backend/opengl/PipelineLayoutGL.cpp, src/backend/opengl/PipelineLayoutGL.h, src/backend/opengl/SamplerGL.cpp, src/backend/opengl/SamplerGL.h, src/backend/opengl/ShaderModuleGL.cpp, src/backend/opengl/ShaderModuleGL.h, src/backend/opengl/TextureGL.cpp, src/backend/opengl/TextureGL.h
This is to trigger a travis build, please do not land.
=> Some cleanups found when testing warnings.

examples/CHelloTriangle.cpp, examples/glTFViewer/glTFViewer.cpp, next.json, src/backend/RenderPass.cpp, src/backend/RenderPass.h, src/backend/Texture.cpp, src/backend/Texture.h, src/backend/d3d12/CommandBufferD3D12.cpp, src/backend/d3d12/D3D12Backend.cpp, src/backend/d3d12/D3D12Backend.h, src/backend/d3d12/FramebufferD3D12.cpp, src/backend/d3d12/FramebufferD3D12.h, src/backend/d3d12/TextureD3D12.cpp, src/backend/d3d12/TextureD3D12.h, src/backend/metal/CommandBufferMTL.mm, src/backend/metal/MetalBackend.h, src/backend/metal/MetalBackend.mm, src/backend/metal/TextureMTL.mm, src/backend/opengl/CommandBufferGL.cpp, src/backend/opengl/OpenGLBackend.cpp, src/backend/opengl/OpenGLBackend.h, src/backend/opengl/TextureGL.cpp, src/utils/D3D12Binding.cpp, src/utils/NXTHelpers.cpp
=> Add depth-stencil textures and attachments

examples/Animometer.cpp, examples/CHelloTriangle.cpp, examples/ComputeBoids.cpp, examples/HelloCompute.cpp, examples/HelloDepthStencil.cpp, examples/HelloIndices.cpp, examples/HelloInstancing.cpp, examples/HelloTriangle.cpp, examples/HelloUBO.cpp, examples/HelloVertices.cpp, examples/RenderToTexture.cpp, examples/SampleUtils.cpp, examples/glTFViewer/glTFViewer.cpp, src/backend/d3d12/BufferD3D12.cpp, src/backend/metal/MetalBackend.mm, src/tests/CMakeLists.txt, src/tests/NXTTest.cpp, src/tests/NXTTest.h, src/tests/end2end/BufferTests.cpp, src/utils/CMakeLists.txt, src/utils/SystemUtils.cpp, src/utils/SystemUtils.h
=> Map read tests

src/tests/NXTTest.cpp, src/tests/NXTTest.h, src/tests/end2end/BufferTests.cpp
=> Add tests for BufferSetSubData

generator/CMakeLists.txt, next.json, src/backend/CommandBuffer.cpp, src/backend/CommandBuffer.h, src/backend/CommandBufferStateTracker.cpp, src/backend/CommandBufferStateTracker.h, src/backend/Commands.h, src/backend/ShaderModule.cpp, src/backend/opengl/CommandBufferGL.cpp, src/tests/CMakeLists.txt, src/tests/unittests/validation/InputStateValidationTests.cpp, src/tests/unittests/validation/PushConstantsValidationTests.cpp, src/tests/unittests/validation/ValidationTest.cpp, src/tests/unittests/validation/ValidationTest.h
PTAL, end2end tests for push constants will follow.
=> Add push constant validation tests

generator/templates/wire/WireClient.cpp, src/backend/Builder.cpp, src/tests/unittests/WireTests.cpp
=> Forward unhandled builder errors to the device

src/backend/ShaderModule.cpp, src/backend/ShaderModule.h, src/backend/d3d12/ShaderModuleD3D12.cpp, src/backend/metal/CommandBufferMTL.mm, src/backend/metal/ComputePipelineMTL.mm, src/backend/metal/InputStateMTL.mm, src/backend/metal/PipelineLayoutMTL.mm, src/backend/metal/RenderPipelineMTL.mm, src/backend/metal/ShaderModuleMTL.h, src/backend/metal/ShaderModuleMTL.mm
PTAL, this fixes the Metal binding model that was "how did this even work" before.
Also, push constants.
Will fix #58
=> Metal binding model

examples/glTFViewer/glTFViewer.cpp
This fixes the issue where the default texture wasn't uploading
correctly (due to 3f47729, changes in row pitch validation) by just
removing the broken texture entirely.
=> glTFViewer: replace default texture with an untextured shader

src/backend/d3d12/CommandBufferD3D12.cpp
Dunno how I lost these. Did something wrong with a rebase.
Merging now.
=> Typo fixes accidentally lost from #105

.travis.yml
=> Pin travis to precise until we can upgrade to trusty

src/backend/Framebuffer.cpp, src/backend/RenderPass.cpp, src/backend/opengl/CommandBufferGL.cpp, src/tests/CMakeLists.txt, src/tests/NXTTest.cpp, src/tests/NXTTest.h, src/tests/end2end/RenderPassLoadOpTests.cpp, src/tests/unittests/validation/FramebufferValidationTests.cpp, src/tests/unittests/validation/RenderPassValidationTests.cpp
~~Includes commits from #105. Will rebase once it lands.~~
=> Add tests for clears, render passes, framebuffers

src/tests/end2end/RenderPassLoadOpTests.cpp
Tests that an attachment is cleared only on the first subpass that uses it in a renderpass.
=> RenderPassLoadOpTests.ClearsOnlyOnFirstUsePerRenderPass

src/backend/BindGroup.cpp
=> Fix indexing error

src/backend/CommandBufferStateTracker.cpp
=> Remove the last few null=backbuffer hacks

CMakeLists.txt, examples/Animometer.cpp, examples/CHelloTriangle.cpp, examples/ComputeBoids.cpp, examples/HelloCompute.cpp, examples/HelloDepthStencil.cpp, examples/HelloIndices.cpp, examples/HelloInstancing.cpp, examples/HelloTriangle.cpp, examples/HelloUBO.cpp, examples/HelloVertices.cpp, examples/RenderToTexture.cpp, examples/glTFViewer/glTFViewer.cpp, next.json, src/backend/SwapChain.cpp, src/backend/SwapChain.h, src/backend/Texture.cpp, src/backend/Texture.h, src/backend/d3d12/CommandBufferD3D12.cpp, src/backend/d3d12/TextureD3D12.h, src/backend/metal/TextureMTL.h, src/backend/null/NullBackend.h, src/backend/opengl/TextureGL.cpp, src/backend/opengl/TextureGL.h, src/include/nxt/nxt_wsi.h, src/tests/NXTTest.cpp, src/utils/D3D12Binding.cpp, src/utils/MetalBinding.mm, src/utils/OpenGLBinding.cpp, src/utils/SwapChainImpl.h
=> Configure texture usage for Swap Chains

generator/main.py, generator/templates/blink/Forward.h, generator/templates/blink/Object.h, generator/templates/blink/Object.idl, generator/templates/blink/Objects.cpp
This both makes changes to follow changes in Blink and adds stubs for
SetFooCallback methods
=> Update Blink integration

src/backend/CMakeLists.txt, src/backend/opengl/BufferGL.h, src/backend/opengl/CommandBufferGL.cpp, src/backend/opengl/GeneratedCodeIncludes.h, src/backend/opengl/InputStateGL.cpp, src/backend/opengl/InputStateGL.h, src/backend/opengl/OpenGLBackend.cpp, src/backend/opengl/OpenGLBackend.h, src/backend/opengl/RenderPipelineGL.cpp, src/tests/NXTTest.h, src/tests/end2end/IndexFormatTests.cpp
=> Lazy vertex/index buffer application in GL

src/backend/CMakeLists.txt, src/backend/vulkan/BufferUploader.cpp, src/backend/vulkan/BufferUploader.h, src/backend/vulkan/BufferVk.cpp, src/backend/vulkan/VulkanBackend.cpp, src/backend/vulkan/VulkanBackend.h, src/include/nxt/nxt_wsi.h, src/tests/end2end/BufferTests.cpp, src/utils/VulkanBinding.cpp
=> Get to first passing test on Vulkan

.travis.yml
=> Travis: install pip manually on OSX

.appveyor.yml, .travis.yml, CMakeLists.txt, examples/Animometer.cpp, examples/CHelloTriangle.cpp, examples/ComputeBoids.cpp, examples/HelloCompute.cpp, examples/HelloDepthStencil.cpp, examples/HelloIndices.cpp, examples/HelloInstancing.cpp, examples/HelloTriangle.cpp, examples/HelloUBO.cpp, src/tests/end2end/PrimitiveTopologyTests.cpp, src/tests/end2end/RenderPassLoadOpTests.cpp, src/tests/unittests/validation/InputStateValidationTests.cpp, src/tests/unittests/validation/RenderPipelineValidationTests.cpp, src/tests/unittests/validation/VertexBufferValidationTests.cpp, src/utils/CMakeLists.txt, third_party/CMakeLists.txt
=> Binary size / compilation speed

src/backend/Buffer.cpp, src/backend/Buffer.h, src/backend/CMakeLists.txt, src/backend/Commands.h, src/backend/vulkan/BufferUploader.cpp, src/backend/vulkan/BufferVk.cpp, src/backend/vulkan/BufferVk.h, src/backend/vulkan/CommandBufferVk.cpp, src/backend/vulkan/CommandBufferVk.h, src/backend/vulkan/FencedDeleter.cpp, src/backend/vulkan/FencedDeleter.h, src/backend/vulkan/GeneratedCodeIncludes.h, src/backend/vulkan/MemoryAllocator.cpp, src/backend/vulkan/MemoryAllocator.h, src/backend/vulkan/VulkanBackend.cpp, src/backend/vulkan/VulkanBackend.h, src/backend/vulkan/vulkan_platform.h, src/tests/end2end/BufferTests.cpp
=> Implement buffer copies and transitions

src/backend/CMakeLists.txt, src/backend/Texture.cpp, src/backend/Texture.h, src/backend/vulkan/CommandBufferVk.cpp, src/backend/vulkan/FencedDeleter.cpp, src/backend/vulkan/FencedDeleter.h, src/backend/vulkan/GeneratedCodeIncludes.h, src/backend/vulkan/TextureVk.cpp, src/backend/vulkan/TextureVk.h, src/backend/vulkan/VulkanBackend.cpp, src/backend/vulkan/VulkanBackend.h, src/tests/end2end/CopyTests.cpp
Still needs formatting, will get the diff from the tryjobs.
=> Vulkan: Implement textures and B<->T texture copies

src/backend/CMakeLists.txt, src/backend/vulkan/CommandBufferVk.cpp, src/backend/vulkan/FencedDeleter.cpp, src/backend/vulkan/FencedDeleter.h, src/backend/vulkan/NativeSwapChainImplVk.cpp, src/backend/vulkan/NativeSwapChainImplVk.h, src/backend/vulkan/TextureVk.cpp, src/backend/vulkan/TextureVk.h, src/backend/vulkan/VulkanBackend.cpp, src/backend/vulkan/VulkanBackend.h, src/common/vulkan_platform.h, src/utils/VulkanBinding.cpp
=> Vulkan: Initial swapchain implementation

src/backend/BindGroup.cpp, src/backend/BindGroup.h, src/backend/BindGroupLayout.cpp, src/backend/BindGroupLayout.h, src/backend/CMakeLists.txt, src/backend/metal/SwapChainMTL.h, src/backend/opengl/BlendStateGL.h, src/backend/opengl/PersistentPipelineStateGL.h, src/backend/vulkan/BindGroupLayoutVk.cpp, src/backend/vulkan/BindGroupLayoutVk.h, src/backend/vulkan/BindGroupVk.cpp, src/backend/vulkan/BindGroupVk.h, src/backend/vulkan/BlendStateVk.cpp, src/backend/vulkan/BlendStateVk.h, src/backend/vulkan/CommandBufferVk.cpp, src/backend/vulkan/FencedDeleter.cpp, src/backend/vulkan/FencedDeleter.h, src/backend/vulkan/GeneratedCodeIncludes.h, src/backend/vulkan/InputStateVk.h, src/backend/vulkan/PipelineLayoutVk.cpp, src/backend/vulkan/RenderPipelineVk.cpp, src/backend/vulkan/VulkanBackend.cpp, src/backend/vulkan/VulkanBackend.h, src/tests/end2end/BlendStateTests.cpp
PTAL! I thought I could enable BlendStateTest just by implementing BlendState but it turns out it uses a UBO so I implemented that too!
=> Vulkan: Implement BlendState, BindGroups and  UBOs

src/backend/CMakeLists.txt, src/backend/vulkan/CommandBufferVk.cpp, src/backend/vulkan/DepthStencilStateVk.cpp, src/backend/vulkan/DepthStencilStateVk.h, src/backend/vulkan/GeneratedCodeIncludes.h, src/backend/vulkan/RenderPassVk.cpp, src/backend/vulkan/RenderPipelineVk.cpp, src/backend/vulkan/TextureVk.cpp, src/backend/vulkan/VulkanBackend.cpp, src/backend/vulkan/VulkanBackend.h, src/tests/end2end/DepthStencilStateTests.cpp
=> Vulkan: Enable DepthStencilStateTests

scripts/travis_lint_format.sh, src/backend/metal/ShaderModuleMTL.mm, src/tests/CMakeLists.txt, src/tests/end2end/BlendStateTests.cpp, src/tests/end2end/InputStateTests.cpp, src/tests/end2end/PushConstantTests.cpp, src/tests/end2end/ViewportOrientationTests.cpp, src/utils/NXTHelpers.cpp, src/utils/NXTHelpers.h, src/utils/OpenGLBinding.cpp
=> Orientation

next.json, src/backend/CommandBuffer.cpp, src/backend/CommandBuffer.h, src/backend/Commands.h, src/backend/d3d12/CommandBufferD3D12.cpp, src/backend/metal/CommandBufferMTL.mm, src/backend/opengl/CommandBufferGL.cpp, src/backend/opengl/OpenGLBackend.cpp, src/backend/vulkan/CommandBufferVk.cpp, src/tests/CMakeLists.txt, src/tests/end2end/BlendStateTests.cpp, src/tests/end2end/DepthStencilStateTests.cpp, src/tests/end2end/ScissorTests.cpp, src/tests/end2end/ViewportOrientationTests.cpp, src/tests/unittests/validation/DynamicStateCommandValidationTests.cpp
=> Add SetScissorRect

src/backend/opengl/TextureGL.cpp
=> Use GL_RGBA8 as the internal format for GL_BGRA.

next.json, src/backend/InputState.cpp, src/backend/InputState.h, src/backend/d3d12/InputStateD3D12.cpp, src/backend/metal/InputStateMTL.mm, src/backend/opengl/CommandBufferGL.cpp, src/tests/end2end/InputStateTests.cpp
This likely requires a test in InputStateTests, but I'm not sure exactly how. Suggestions?
=> Implement UnormR8G8B8A8 vertex format.

next.json, src/backend/Sampler.cpp, src/backend/Sampler.h, src/backend/d3d12/SamplerD3D12.cpp, src/backend/metal/SamplerMTL.mm, src/backend/opengl/SamplerGL.cpp, src/tests/CMakeLists.txt, src/tests/end2end/SamplerTests.cpp
Implement sampler address modes (repeat, mirrored repeat, clamp-to-edge).
Add an end-to-end test for Samplers.
=> Address modes

src/backend/opengl/BlendStateGL.cpp, src/tests/end2end/BlendStateTests.cpp
Set the color mask even if blending is disabled.
=> Fix color write mask on GL backend.

src/backend/BindGroupLayout.cpp, src/backend/Device.cpp, src/backend/PipelineLayout.cpp, src/backend/RefCounted.cpp, src/backend/vulkan/RenderPassVk.cpp, src/backend/vulkan/VulkanBackend.cpp, src/tests/unittests/RefCountedTests.cpp
PTAL, coming back to the Vulkan backend with updated validation layers uncovered a number of issues.
=> Vulkan fixes

generator/templates/wire/WireClient.cpp, generator/templates/wire/WireCmd.h, generator/templates/wire/WireServer.cpp, src/tests/unittests/WireTests.cpp, src/wire/WireCmd.h
PTAL @SenorBlanco and @kainino0x
=> Wire: Implement MapWriteAsync

src/backend/metal/DeviceMTL.mm
Fixes a crash for me on macOS+Metal
=> Manually retain/release mPendingCommands

src/backend/d3d12/BufferD3D12.cpp, src/backend/d3d12/BufferD3D12.h, src/backend/d3d12/CommandBufferD3D12.cpp, src/backend/d3d12/CommandBufferD3D12.h, src/backend/d3d12/DeviceD3D12.cpp, src/backend/d3d12/NativeSwapChainImplD3D12.cpp, src/backend/d3d12/QueueD3D12.cpp, src/backend/d3d12/SwapChainD3D12.cpp, src/backend/d3d12/SwapChainD3D12.h, src/backend/d3d12/TextureD3D12.cpp, src/backend/d3d12/TextureD3D12.h
=> Implement naive implicit barriers on the D3D12 backend.

examples/glTFViewer/Camera.inl, examples/glTFViewer/glTFViewer.cpp
Doesn't completely fix the viewer - there is still a TODO about uniform buffers being updated incorrectly.
=> Partially fix glTFViewer (bind group + y-flip)

examples/glTFViewer/glTFViewer.cpp
* Works on Metal
* Not working on OpenGL (black screen; not sure why)
* Not working on Vulkan or D3D12 (assertion crash; push constants aren't implemented?)
=> Fix glTFViewer by using push constants

src/backend/CommandBuffer.cpp, src/backend/CommandBuffer.h, src/backend/CommandBufferStateTracker.cpp, src/backend/CommandBufferStateTracker.h
=> State tracker

src/backend/Buffer.cpp, src/backend/Buffer.h
=> BufferBase: Split validation in helper methods

.gitignore, .gn, BUILD.gn, DEPS, build_overrides/build.gni, build_overrides/dawn.gni, examples/SampleUtils.cpp, generator/main.py, generator/templates/dawn_native/ProcTable.cpp, src/Empty.cpp, src/dawn_native/CMakeLists.txt, src/dawn_native/DawnNative.cpp, src/dawn_native/d3d12/DeviceD3D12.cpp, src/dawn_native/metal/DeviceMTL.mm, src/dawn_native/null/NullBackend.cpp, src/dawn_native/opengl/DeviceGL.cpp, src/dawn_native/vulkan/DeviceVk.cpp, src/include/dawn_native/D3D12Backend.h, src/include/dawn_native/DawnNative.h, src/include/dawn_native/NullBackend.h, src/include/dawn_native/OpenGLBackend.h, src/include/dawn_native/VulkanBackend.h, src/tests/DawnTest.cpp, src/tests/unittests/validation/ValidationTest.cpp, src/utils/BackendBinding.h, src/utils/D3D12Binding.cpp, src/utils/MetalBinding.mm, src/utils/NullBinding.cpp, src/utils/OpenGLBinding.cpp, src/utils/VulkanBinding.cpp
=> Initial BUILD.gn files so that it can be used for Skia-Dawn

BUILD.gn, build_overrides/dawn.gni, src/tests/unittests/EnumClassBitmasksTests.cpp, src/tests/unittests/MathTests.cpp, src/tests/unittests/SerialQueueTests.cpp, src/utils/VulkanBinding.cpp
=> Other pre-BUILD.gn changes

.travis.yml, BUILD.gn, DEPS, build_overrides/dawn.gni, build_overrides/spirv_tools.gni, scripts/dawn_overrides_with_defaults.gni, src/utils/D3D12Binding.cpp, third_party/BUILD.gn
=> BUILD.gn up to tests

OWNERS, README.chromium, README.md
=> README files for Dawn.

dawn.json, src/dawn_native/Device.cpp, src/dawn_native/Device.h, src/dawn_native/ShaderModule.cpp, src/dawn_native/ShaderModule.h, src/dawn_native/d3d12/DeviceD3D12.cpp, src/dawn_native/d3d12/DeviceD3D12.h, src/dawn_native/d3d12/ShaderModuleD3D12.cpp, src/dawn_native/d3d12/ShaderModuleD3D12.h, src/dawn_native/metal/DeviceMTL.h, src/dawn_native/metal/DeviceMTL.mm, src/dawn_native/metal/ShaderModuleMTL.h, src/dawn_native/metal/ShaderModuleMTL.mm, src/dawn_native/null/NullBackend.cpp, src/dawn_native/null/NullBackend.h, src/dawn_native/opengl/DeviceGL.cpp, src/dawn_native/opengl/DeviceGL.h, src/dawn_native/opengl/ShaderModuleGL.cpp, src/dawn_native/opengl/ShaderModuleGL.h, src/dawn_native/vulkan/DeviceVk.cpp, src/dawn_native/vulkan/DeviceVk.h, src/dawn_native/vulkan/ShaderModuleVk.cpp, src/dawn_native/vulkan/ShaderModuleVk.h, src/tests/unittests/WireTests.cpp, src/tests/unittests/validation/InputStateValidationTests.cpp, src/tests/unittests/validation/PushConstantsValidationTests.cpp, src/utils/DawnHelpers.cpp, src/utils/DawnHelpers.h
=> Descriptorize ShaderModule

src/common/HashUtils.h
This fixes the GN debug build on Linux.
PTAL @SenorBlanco @Jiawei-Shao
=> Workaround a _GLIBCXX_DEBUG bug for std::hash<std::bitset>

PRESUBMIT.py, codereview.settings, infra/config/OWNERS, infra/config/README.md, infra/config/branch/cq.cfg, infra/config/global/cr-buildbucket.cfg, infra/config/global/luci-logdog.cfg, infra/config/global/luci-milo.cfg, infra/config/global/luci-scheduler.cfg, infra/config/global/project.cfg, infra/config/global/refs.cfg
[This has already been reviewed by Chrome infra on our Gerrit.](https://dawn-review.googlesource.com/c/dawn/+/1100)
@kainino0x TBR
=> Initial CQ configuration

infra/config/global/luci-scheduler.cfg
=> Fix typos in cr-builbucket.cfg

src/common/vulkan_platform.h
On 32bit platforms, even if it contains a uint64_t the handle wrapper
will align to 4 bytes because the assembly load operations can't take
advantage of 64bit aligned loads.
Fix this by forcing the alignment to the alignment of what would be the
native Vulkan handle type.
PTAL @SenorBlanco @kainino0x
=> Fix VkNonDispatchableHandle's alignment on 32bit platforms

.gitmodules, DEPS, src/dawn_native/ShaderModule.cpp, src/dawn_native/d3d12/ShaderModuleD3D12.cpp, src/dawn_native/metal/ComputePipelineMTL.mm, src/dawn_native/metal/RenderPipelineMTL.mm, src/dawn_native/metal/ShaderModuleMTL.h, src/dawn_native/metal/ShaderModuleMTL.mm, src/dawn_native/opengl/ShaderModuleGL.cpp
=> Roll SPIRV-Cross and use Chromium git mirrors in DEPS

infra/config/global/luci-scheduler.cfg
=> Make all CI bots scheduled by the gittiles trigger

src/dawn_native/vulkan/DeviceVk.cpp
Hide vktrace layout behide a marco 'DAWN_USE_VKTRACE' and enable it in build if needed.
=> Vulkan: add macro for vktrace

src/common/vulkan_platform.h
There alignof(uint64_t) is 8 but it is aligned to 4 inside structures.
PTAL @SenorBlanco @kainino0x
=> Fix VkNonDispatchableHandle alignment on Linux x86

infra/config/branch/cq.cfg, infra/config/global/cr-buildbucket.cfg, infra/config/global/luci-milo.cfg
This has already been reviewed on https://dawn-review.googlesource.com/c/dawn/+/1380
=> infra: Add a presubmit builder to the CQ.

BUILD.gn, DEPS, src/dawn_native/CMakeLists.txt, src/dawn_native/ShaderModule.cpp, src/tests/CMakeLists.txt, src/tests/unittests/validation/ShaderModuleValidationTests.cpp, src/tests/unittests/validation/ValidationTest.cpp, src/tests/unittests/validation/ValidationTest.h, src/utils/DawnHelpers.cpp, src/utils/DawnHelpers.h, third_party/BUILD.gn, third_party/CMakeLists.txt
=> Validate ShaderModule's SPIRV

.gn, DEPS, PRESUBMIT.py, scripts/lint_clang_format.sh, scripts/travis_lint_format.sh
@kainino0x PTAL. I'm waiting for a gclient CL to land to be able to check that this works on the CQ, but I'm 95% sure it will. Asking for a review now to gain 1 day of latency if everything works correctly.
=> Add formatting checks to PRESUBMIT.py
