google/nxt-standalone

examples/HelloTriangle.cpp
examples/glTFViewer/glTFViewer.cpp
generator/templates/mock_api.cpp
generator/templates/mock_api.h
next.json
src/backend/common/CommandBuffer.cpp
src/backend/common/CommandBuffer.h
src/backend/common/Commands.h
src/backend/metal/MetalBackend.mm
src/backend/opengl/CommandBufferGL.cpp

PTAL, this removes the gMock issue blocking #9 and adds bufferOffset to Buffer -> Texture copies. Missing arguments are rowLength, imageHeight and which aspects to copy, which aren't too useful.

CopyBufferToTexture buffer offset

---

generator/main.py
generator/templates/apicpp.h
generator/templates/apicpp_traits.h
src/backend/common/Builder.cpp
src/tests/CMakeLists.txt
src/tests/unittests/ObjectBaseTests.cpp
src/tests/unittests/WireTests.cpp
src/tests/unittests/validation/BufferValidationTest.cpp
src/tests/unittests/validation/ValidationTest.cpp
src/tests/unittests/validation/ValidationTest.h

PTAL, this is adds the skeleton of validation tests.
I went through many iterations to try to make this work seamlessly with an added wire between the test code and the null backend, but didn't find a good way to do it (I stopped short of generating a whole new nxtcpp just for test purpose).
If we ever want to make validation tests work with the wire, we could create an alternative to TerribleCommandBuffer that doesn't buffer at all and basically makes all nxt calls synchronous.

Validation tests

---

.travis.yml

Fixes #37. Build failures were happening because g++ was running out of memory. This PR removes gcc and only builds with clang on Travis

Remove gcc from Travis CI builds

---

src/backend/CMakeLists.txt
src/backend/common/CommandBuffer.cpp
src/backend/common/CommandBuffer.h
src/backend/common/CommandBufferStateTracker.cpp
src/backend/common/CommandBufferStateTracker.h

Dependent on #18, so this will be easier to review after that's merged and this is rebased. Defer if you want.
Later (after this lands) I plan to move more of the logic from CommandBuffer.cpp to CommandBufferStateTracker.cpp.

Create a command buffer builder state tracker object

---

examples/D3D12Binding.cpp
src/backend/d3d12/CommandBufferD3D12.cpp
src/backend/d3d12/D3D12Backend.cpp
src/backend/d3d12/D3D12Backend.h
src/backend/d3d12/QueueD3D12.cpp
src/backend/d3d12/QueueD3D12.h

- Moves resource barriers from the D3D12 backend to the binding. Previously, resource transitions between `D3D12_RESOURCE_STATE_RENDER_TARGET` and `D3D12_RESOURCE_STATE_PRESENT` were done at the start and end of every render pass. This is incorrect and should only be done when the render target changes and buffers are swapped.
- With the binding handling the frame transitions, each frame has it's own `ID3D12CommandAllocator` so the next frame can be started before the current frame is done. This is what Microsoft shows to do in their frame buffering [example](https://github.com/Microsoft/DirectX-Graphics-Samples/blob/master/Samples/Desktop/D3D12HelloWorld/src/HelloFrameBuffering/D3D12HelloFrameBuffering.cpp)
- Fix which prevents a `Queue` from resetting an `ID3D12CommandAllocator` before …

Move Resource Barriers to D3D12 Binding

---

examples/ComputeBoids.cpp
examples/HelloCompute.cpp
examples/HelloDepthStencil.cpp
examples/HelloIndices.cpp
examples/HelloInstancing.cpp
examples/HelloTriangle.cpp
examples/HelloUBO.cpp
examples/HelloVertices.cpp
examples/RenderToTexture.cpp
examples/Utils.cpp
examples/glTFViewer/glTFViewer.cpp
next.json
src/backend/common/Buffer.cpp

Also make use of CreateFrozenBufferFromData where possible in the
example to make the renaming easier.

Split Mapped usage in MapWrite and MapRead

---

examples/D3D12Binding.cpp
src/backend/CMakeLists.txt
src/backend/common/SerialQueue.h
src/backend/d3d12/BufferD3D12.cpp
src/backend/d3d12/BufferD3D12.h
src/backend/d3d12/CommandAllocatorManager.cpp
src/backend/d3d12/CommandAllocatorManager.h
src/backend/d3d12/D3D12Backend.cpp
src/backend/d3d12/D3D12Backend.h
src/backend/d3d12/QueueD3D12.cpp
src/backend/d3d12/QueueD3D12.h
src/backend/d3d12/ResourceAllocator.cpp
src/backend/d3d12/ResourceAllocator.h
src/backend/d3d12/ResourceUploader.cpp
src/backend/d3d12/ResourceUploader.h

- Adds `CommandAllocatorManager` to manage creation and lifetimes of `ID3D12CommandAllocator`s using a `SerialQueue`. On `Device::TickImpl`, old Command Allocators will be reset so a Command Allocator must be used before the next Tick.
- Adds `ExecuteCommandLists` to the device to ensure that pending commands are always executed first
- Adds `ResourceAllocationManager` to manage creation of `ID3D12Resource`s. This is currently a simple interface which always uses `CreateCommittedResource`. Freeing resources places them on a `SerialQueue` to be released when the GPU finishes work up to the current serial. Freeing them is currently totally unnecessary because they won't actually be freed until the ComPtr is released, but is implemented so that it will be easier to replace resources with …

Introduce Allocation Managers to the D3D12 backend

---

src/backend/common/SerialQueue.h
src/tests/unittests/SerialQueueTests.cpp

Adds a test for SerialQueue::FirstSerial
I also noticed that SerialQueue::Enque on empty vectors would break things (and wouldn't really make sense anyway) so I added an assertion for that case.

Test SerialQueue::FirstSerial

---

next.json
src/backend/common/CommandBuffer.cpp
src/backend/common/CommandBuffer.h
src/backend/common/Commands.h
src/backend/d3d12/CommandBufferD3D12.cpp
src/backend/metal/CommandBufferMTL.mm
src/backend/opengl/CommandBufferGL.cpp
src/tests/unittests/validation/CopyCommandsValidationTests.cpp

PTAL, this will be important to be able to check pixel values in the end2end tests. I didn't actually test that the Metal implementation works though.
Part of #53.

Texture to buffer copies

---

third_party/CMakeLists.txt

Visual Studio 2017 is able to build CMake-based projects directly be
opening the folder containing the CMakeLists.txt. However when doing
this shaderc is not able to find the Python executable (it uses
find_program instead of the special Python CMake module). Help shaderc
by setting the PYTHON_EXE variable before including its CMakeLists.txt

Fix shaderc not finding python when inside VS

---

src/backend/CMakeLists.txt
src/backend/common/CommandBuffer.cpp
src/backend/common/CommandBufferStateTracker.cpp
src/backend/common/Commands.h
src/backend/d3d12/BindGroupD3D12.cpp
src/backend/d3d12/BindGroupD3D12.h
src/backend/d3d12/BindGroupLayoutD3D12.cpp
src/backend/d3d12/BindGroupLayoutD3D12.h
src/backend/d3d12/BufferD3D12.cpp
src/backend/d3d12/BufferD3D12.h
src/backend/d3d12/CommandBufferD3D12.cpp
src/backend/d3d12/D3D12Backend.cpp
src/backend/d3d12/D3D12Backend.h
src/backend/d3d12/DescriptorHeapAllocator.cpp
src/backend/d3d12/DescriptorHeapAllocator.h
src/backend/d3d12/GeneratedCodeIncludes.h
src/backend/d3d12/PipelineD3D12.cpp
src/backend/d3d12/PipelineLayoutD3D12.cpp
src/backend/d3d12/PipelineLayoutD3D12.h
src/backend/d3d12/SamplerD3D12.cpp
src/backend/d3d12/SamplerD3D12.h
src/backend/d3d12/ShaderModuleD3D12.cpp
src/backend/d3d12/TextureD3D12.cpp
src/backend/d3d12/TextureD3D12.h

This is mostly one commit because I couldn't really test anything until all the parts were in place, but if it's easier, I can split it up
- Textures and samplers are currently untested because buffer->texture copies are not yet implemented.
- Allocation of descriptor heaps is currently only does a simple linear allocation and all heaps are both CPU and GPU visible. This will need to be changed in the future.

Add D3D12 Buffer, Texture, and Sampler binding

---

src/backend/d3d12/BufferD3D12.cpp
src/backend/d3d12/BufferD3D12.h
src/backend/d3d12/CommandAllocatorManager.cpp
src/backend/d3d12/CommandAllocatorManager.h
src/backend/d3d12/CommandBufferD3D12.cpp
src/backend/d3d12/D3D12Backend.cpp
src/backend/d3d12/D3D12Backend.h
src/backend/d3d12/DescriptorHeapAllocator.cpp
src/backend/d3d12/DescriptorHeapAllocator.h
src/backend/d3d12/ResourceAllocator.cpp
src/backend/d3d12/ResourceAllocator.h
src/backend/d3d12/ResourceUploader.cpp
src/backend/d3d12/ResourceUploader.h
src/backend/d3d12/TextureD3D12.cpp
src/backend/d3d12/TextureD3D12.h
src/tests/NXTTest.cpp
src/tests/NXTTest.h
src/tests/end2end/BasicTests.cpp

This introduces Buffer->Buffer copies, Buffer->Texture copies, Texture->Buffer copies, and MapReadAsync to the D3D12 backend which will help bring us closer to automated testing.
Currently texture operations only work if the rows are 256-byte aligned, but this constraint is not enforced anywhere, so using textures of non-aligned sizes will cause errors.
Buffers with MapRead allowed are created on the READBACK heap and always add the D3D12_RESOURCE_STATE_COPY_DEST state (required by D3D12). Likewise MapWrite adds the D3D12_RESOURCE_STATE_GENERIC_READ state and places resources on the UPLOAD heap. Because these states are required, transitions for mapped buffers do nothing.
A small test which does a Buffer->Texture and then Texture->Buffer copy has been added and is currently working on the …

D3D12: Add MapReadAsync and Resource Copies

---

examples/Animometer.cpp
examples/ComputeBoids.cpp
examples/HelloCompute.cpp
examples/HelloDepthStencil.cpp
examples/HelloIndices.cpp
examples/HelloInstancing.cpp
examples/HelloTriangle.cpp
examples/HelloUBO.cpp
examples/HelloVertices.cpp
examples/RenderToTexture.cpp
examples/glTFViewer/glTFViewer.cpp
next.json
src/backend/CommandBuffer.cpp
src/backend/CommandBuffer.h
src/backend/CommandBufferStateTracker.cpp
src/backend/CommandBufferStateTracker.h
src/backend/Commands.h
src/backend/d3d12/CommandBufferD3D12.cpp
src/backend/metal/CommandBufferMTL.mm
src/backend/opengl/CommandBufferGL.cpp

This change is motivated by usage transitions: if there are usage transitions in between subpasses, AdvanceSubpass makes it unnatural. Plus, if we go the route of all-explicit attachment transitions, they have to be done between subpasses.
TODO:

replace AdvanceSubpass with Begin/EndRenderSubpass

---

examples/RenderToTexture.cpp
next.json
src/backend/CommandBufferStateTracker.cpp
src/backend/CommandBufferStateTracker.h
src/backend/Texture.cpp
src/backend/Texture.h
src/backend/d3d12/TextureD3D12.cpp
src/backend/metal/TextureMTL.mm
src/tests/end2end/InputStateTests.cpp

Also changes the attachment usages to OutputAttachment and InputAttachment instead of ColorAttachment, DepthStencilAttachment, etc.
~~Based on top of #64, so there's an extra commit in here.~~

Freeze texture transitions while attached

---

src/backend/Device.cpp
src/backend/Device.h
src/backend/d3d12/D3D12Backend.cpp
src/backend/d3d12/D3D12Backend.h
src/backend/metal/MetalBackend.h
src/backend/metal/MetalBackend.mm
src/backend/null/NullBackend.cpp
src/backend/null/NullBackend.h
src/backend/opengl/OpenGLBackend.cpp
src/backend/opengl/OpenGLBackend.h

Adds reference counting to the device and deletes itself when it reaches 0
D3D12 backend waits for GPU execution to complete when destroyed

Add reference counting to DeviceBase

---

examples/ComputeBoids.cpp
examples/HelloCompute.cpp
next.json
src/backend/CommandBuffer.cpp
src/backend/CommandBuffer.h
src/backend/CommandBufferStateTracker.cpp
src/backend/CommandBufferStateTracker.h
src/backend/Commands.h
src/backend/d3d12/CommandBufferD3D12.cpp
src/backend/metal/CommandBufferMTL.mm
src/backend/opengl/CommandBufferGL.cpp

`SetPipeline(computePipeline)` is gated on `BeginComputePass`, so that should cover the necessary validation, at least for `Dispatch`.

Introduce Begin/EndComputePass

---

src/backend/CommandBuffer.cpp
src/backend/CommandBuffer.h
src/backend/opengl/CommandBufferGL.cpp
src/backend/opengl/OpenGLBackend.cpp
src/backend/opengl/OpenGLBackend.h
src/utils/OpenGLBinding.cpp

Probably not the most efficient implementation, but works.
Issues:

OpenGL backend: implement render passes

---

src/backend/CMakeLists.txt
src/backend/d3d12/CommandBufferD3D12.cpp
src/backend/d3d12/D3D12Backend.cpp
src/backend/d3d12/D3D12Backend.h
src/backend/d3d12/FramebufferD3D12.cpp
src/backend/d3d12/FramebufferD3D12.h
src/backend/d3d12/GeneratedCodeIncludes.h
src/backend/d3d12/TextureD3D12.cpp
src/backend/d3d12/TextureD3D12.h
src/tests/NXTTest.cpp
src/tests/NXTTest.h
src/tests/end2end/InputStateTests.cpp
src/utils/D3D12Binding.cpp

Implements BeginRenderSubpass on the D3D12 backend. Descriptors for render target and depth stencil views are recorded in a descriptor heap for each framebuffer. For now, we still have the hack where no attachment renders to the backbuffer, so the CommandBuffer records those when necessary when it is submitted.
This PR also enables input states for D3D12 which are mostly working. One failure seems to be happening because our texture copies are not yet correct.

D3D12 Render Targets

---

src/backend/CMakeLists.txt
src/backend/opengl/BufferGL.cpp
src/backend/opengl/BufferGL.h
src/backend/opengl/CommandBufferGL.cpp
src/backend/opengl/GeneratedCodeIncludes.h
src/backend/opengl/OpenGLBackend.cpp
src/backend/opengl/OpenGLBackend.h
src/backend/opengl/ShaderModuleGL.cpp
src/tests/NXTTest.cpp
src/tests/NXTTest.h
src/tests/end2end/BasicTests.cpp
src/utils/OpenGLBinding.cpp

PTAL this implements the missing features that were required to run some test on OpenGL. Note that the T->B copy implementation conflicts with the rowPitch PR as it doesn't do the rowPitch alignment for now.

OpenGL backend: implement features needed for testing

---

examples/HelloDepthStencil.cpp
src/backend/DepthStencilState.cpp
src/backend/DepthStencilState.h
src/backend/metal/DepthStencilStateMTL.mm
src/backend/opengl/DepthStencilStateGL.cpp
src/tests/CMakeLists.txt
src/tests/end2end/DepthStencilStateTests.cpp

This also removes DepthTestEnabled(). This also fixes bugs where depth writes wouldn't work if the depth compare function was `Always`. We were seeing a regression with HelloDepthStencil on Metal, and I believe this is the problem.

Add end2end depth stencil state tests

---

next.json
src/backend/RenderPipeline.cpp
src/backend/RenderPipeline.h
src/backend/d3d12/CommandBufferD3D12.cpp
src/backend/d3d12/RenderPipelineD3D12.cpp
src/backend/d3d12/RenderPipelineD3D12.h
src/backend/metal/CommandBufferMTL.mm
src/backend/metal/RenderPipelineMTL.h
src/backend/metal/RenderPipelineMTL.mm
src/backend/opengl/CommandBufferGL.cpp
src/backend/opengl/RenderPipelineGL.cpp
src/backend/opengl/RenderPipelineGL.h
src/tests/CMakeLists.txt
src/tests/end2end/PrimitiveTopologyTests.cpp
src/tests/unittests/validation/RenderPipelineValidationTests.cpp

Can someone test this on Metal? Not sure they have the same point/line/triangle rasterization rules.
This also alphabetizes some stuff for the RenderPipeline

Add primitive topology

---

src/backend/CMakeLists.txt
src/backend/d3d12/D3D12Backend.cpp
src/utils/D3D12Binding.cpp

This adds better live object reporting in debug mode and fixes a bunch of memory leaks which were happening because I never properly deleted things. Now there are no longer 927 live objects after running the end2end tests :P
I think there are still a couple problems though. It's reporting a ID3D12RootSignature as live when some of the tests exit.

D3D12: Improve live object reporting and actually clean up resources

---

next.json
src/backend/Texture.cpp
src/backend/d3d12/TextureD3D12.cpp
src/backend/metal/TextureMTL.mm

Adds support for RGBA8 integer textures. This is useful for packing data in a g-buffer without risking loss of precision when outputting floats in a fragment shader.

Add RGBA8Uint texture format

---

src/backend/CommandBufferStateTracker.cpp
src/backend/CommandBufferStateTracker.h

This is to avoid a potential future problem if SetPipelineCommon were to
ever return false (which is currently not possible), some state might
have been modified incorrectly.

Change SetPipelineCommon to return void

---

src/backend/d3d12/ShaderModuleD3D12.cpp
src/backend/opengl/ShaderModuleGL.cpp
src/tests/end2end/InputStateTests.cpp
src/tests/end2end/PrimitiveTopologyTests.cpp

This was because the clip space of OpenGL has an inverted Y compared to
other APIs. This commit:
- Updates SPIRV-Cross to the latest version
- Uses the new vertex.flip_vert_y option in ShaderModuleGL
- Enables tests that are now passing in GL.

OpenGL: Fix rendered textures being flipped.

---

src/backend/CMakeLists.txt
src/backend/RefCounted.h
src/backend/d3d12/BufferD3D12.cpp
src/backend/vulkan/BufferVk.cpp
src/backend/vulkan/BufferVk.h
src/backend/vulkan/GeneratedCodeIncludes.h
src/backend/vulkan/MemoryAllocator.cpp
src/backend/vulkan/MemoryAllocator.h
src/backend/vulkan/VulkanBackend.cpp
src/backend/vulkan/VulkanBackend.h
src/backend/vulkan/VulkanFunctions.cpp
src/backend/vulkan/VulkanFunctions.h
src/backend/vulkan/VulkanInfo.cpp
src/backend/vulkan/VulkanInfo.h

PTAL, at this point the VulkanBackend can pass the SetSubData tests with the NXTTest swapchain related code commented out. This is a hack however because everything stays inside `vulkan::Buffer`. I'll add a proper queue, GPU copies, and fencing next. Then a proper "buffer uploader" for SetSubData.

Vulkan: hack SetSubData and MapRead

---

.travis.yml

After LLVM 6.0 was branched, the LLVM APT repositories changed so that
clang-format-6.0 isn't in the "latest" repo but in the "6.0" repo.
Update travis.yml for this, and start using clang-6.0 instead of 5.0.

Fix Travis after LLVM APT repo change

---

src/backend/d3d12/TextureD3D12.cpp

PRESENT is an exclusive flag in NXT and can't be combined with other flags. The existing implementation treats the D3D12_RESOURCE_STATE_PRESENT as flag which is confusing due to being 0.

dx12: Handle present texture in a specially

---

src/backend/d3d12/ComputePipelineD3D12.cpp
src/backend/d3d12/ComputePipelineD3D12.h
src/backend/d3d12/D3D12Backend.cpp
src/backend/d3d12/D3D12Backend.h
src/backend/d3d12/RenderPipelineD3D12.cpp
src/backend/d3d12/RenderPipelineD3D12.h

Previously we would remove the reference to pipelines in the destructor
of the d3d12::*Pipeline objects which could cause the D3D12 pipeline
state to be destroyed while still used by in-flight commands. Add a
global queue of ComPtrs to keep alive in the d3d12::Device to fix this.

D3D12: Keep a reference to pipelines until unused

---

next.json
src/backend/Texture.cpp
src/backend/d3d12/TextureD3D12.cpp
src/backend/metal/TextureMTL.mm
src/backend/opengl/TextureGL.cpp

Backend support added for Metal, D3D12 and OpenGL.
Also fix BGRA support in OpenGL to give it a valid internal format.

Implement R8 and RG8 texture formats with uint and unorm components.

---

src/backend/vulkan/InputStateVk.cpp
src/backend/vulkan/TextureVk.cpp

Implement unorm_rgba8 and unorm_rg8 vertex formats and
{uint8, unorm8} x {r, rg} texture formats on Vulkan backend.

Implement recent vertex and texture formats on Vk.

---

next.json
src/backend/InputState.cpp
src/backend/d3d12/InputStateD3D12.cpp
src/backend/metal/InputStateMTL.mm
src/backend/opengl/CommandBufferGL.cpp
src/backend/vulkan/InputStateVk.cpp

Add support for r16g16 and r16g16b16a16 ushort vertex formats.
(r16 skipped because it requires MacOS 10.13.)

Add support for r16g16 and r16g16b16a16 ushort vertex formats.

---

examples/ComputeBoids.cpp
examples/HelloCompute.cpp
examples/HelloDepthStencil.cpp
examples/HelloUBO.cpp
examples/glTFViewer/glTFViewer.cpp
next.json
src/backend/Buffer.cpp
src/backend/Buffer.h
src/backend/d3d12/BufferD3D12.cpp
src/backend/d3d12/BufferD3D12.h
src/backend/metal/BufferMTL.h
src/backend/metal/BufferMTL.mm
src/backend/null/NullBackend.cpp
src/backend/null/NullBackend.h
src/backend/opengl/BufferGL.cpp
src/backend/opengl/BufferGL.h
src/backend/vulkan/BufferVk.cpp
src/backend/vulkan/BufferVk.h
src/tests/NXTTest.cpp
src/tests/NXTTest.h
src/tests/end2end/BasicTests.cpp
src/tests/end2end/BufferTests.cpp
src/tests/end2end/CopyTests.cpp
src/tests/end2end/PushConstantTests.cpp
src/tests/unittests/validation/BufferValidationTests.cpp
src/tests/unittests/validation/UsageValidationTests.cpp
src/utils/NXTHelpers.cpp

Change the uint32_t offsets in Buffer::SetSubData() to be uint8_ts, rather than uint32_ts.
This makes it practical to do subloads of 16-bit index buffers, for example.

Change Buffer::SetSubData() start and offset to chars

---

next.json
src/backend/InputState.cpp
src/backend/d3d12/InputStateD3D12.cpp
src/backend/metal/InputStateMTL.mm
src/backend/opengl/CommandBufferGL.cpp
src/backend/vulkan/InputStateVk.cpp

Add support for { int } x { rgba32, rgb32, rg32, r32 } vertex formats.

Implement support for all Int32 vertex formats.

---

src/backend/metal/MetalBackend.mm

Without this, the temporary buffers used for SetSubData() uploads never get cleaned up, and eventually will exhaust memory. Note that the D3D12 backend does this also.

Metal backend: do a Tick() on queue submit.

---

scripts/travis_lint_format.sh
src/backend/opengl/CommandBufferGL.cpp

Remove assert for command buffer color binding point texture format. It was triggering on BGRA8, R8, etc.
Here's my reasoning: all color formats we've added so far are renderable. I think only legacy formats (luminance, intensity) and compressed formats are non-renderable. And if we do add non-renderable formats, binding them should probably be caught at validation, not with an assert.

 Expand allowable formats for color attachments

---

src/backend/opengl/CommandBufferGL.cpp

Use a memcpy() to avoid strict-aliasing warnings. Using a union instead would be ideal, but this works for now.

Fix for strict-aliasing issue.

---

src/backend/PipelineLayout.cpp
src/backend/RenderPipeline.cpp
src/backend/SwapChain.cpp

Delete the TextureBuilder created in SwapChainBase::GetNextTexture().
Delete the InputStateBuilder and DepthStencilStateBuilder created in
RenderPipelineBuilder::GetResultImpl().

Fix some leaking builder objects in common backend.

---

scripts/travis_lint_format.sh
src/backend/metal/MetalBackend.mm

GetPendingCommandBuffer() doesn't need to retain the metal
command buffer; it's created with a ref.

Fix leak in Metal's Device::GetPendingCommandBuffer().

---

src/backend/BindGroupLayout.cpp
src/common/CMakeLists.txt
src/common/HashUtils.h
src/common/Platform.h

@kainino0x, @SenorBlanco PTAL, these are changes required for before the PR that will change NXT to use "Metal style" render passes instead of "Vulkan style" ones.

Pre-renderpass changes

---

CMakeLists.txt
generator/templates/backend/ProcTable.cpp
generator/templates/backend/ValidationUtils.cpp
generator/templates/backend/ValidationUtils.h
src/backend/CMakeLists.txt
src/backend/Device.cpp
src/backend/Device.h
src/backend/Error.cpp
src/backend/Error.h
src/backend/ErrorData.cpp
src/backend/ErrorData.h
src/backend/Sampler.cpp
src/backend/Sampler.h
src/backend/d3d12/D3D12Backend.cpp
src/backend/d3d12/D3D12Backend.h
src/backend/metal/MetalBackend.h
src/backend/metal/MetalBackend.mm
src/backend/null/NullBackend.cpp
src/backend/null/NullBackend.h
src/backend/opengl/OpenGLBackend.cpp
src/backend/opengl/OpenGLBackend.h
src/backend/vulkan/VulkanBackend.cpp
src/backend/vulkan/VulkanBackend.h
src/common/CMakeLists.txt
src/common/Compiler.h
src/common/Result.h
src/tests/CMakeLists.txt
src/tests/unittests/ErrorTests.cpp
src/tests/unittests/ResultTests.cpp

PTAL, this adds the foundations of error handling similar to ANGLE's gl::Error and ANGLE_TRY. It is completely overkill for the usage done in this pull-request but will be used throughout NXT eventually.
@kainino0x, @SenorBlanco PTAL!
@vonture FYI as it is similar to a discussion we are having for ANGLE, and also for the fancy C++ usage.

Error handling scaffolding.

---

src/backend/CommandBufferStateTracker.cpp
src/backend/PipelineLayout.cpp
src/backend/PipelineLayout.h
src/backend/d3d12/PipelineLayoutD3D12.cpp
src/backend/metal/PipelineLayoutMTL.mm
src/backend/metal/ShaderModuleMTL.mm
src/backend/opengl/PipelineGL.cpp
src/backend/opengl/PipelineLayoutGL.cpp
src/backend/vulkan/PipelineLayoutVk.cpp
src/backend/vulkan/PipelineLayoutVk.h

Instead of initializing all of the bind group layouts in the pipeline
layout to default values, let them be nullptr and allow this elsewhere.
This is a follow-up on some changes in #206.
Also, rename GetBindGroupsLayoutMask -> GetBindGroupLayoutsMask

Allow bind group layouts to be sparse in pipeline layout

---

examples/ComputeBoids.cpp

I know there was some churn on which version of this shader was correct - but right now, this goes from broken on all 4 backends to working on all 4 backends. So this seems better.
The old code (accidentally?) uses descriptor arrays (I think), which are not trivial to support on all backends, so we won't use them for now.

Fix ComputeBoids

---

examples/SampleUtils.cpp
generator/templates/wire/WireClient.cpp
generator/templates/wire/WireServer.cpp
src/tests/NXTTest.cpp
src/tests/unittests/WireTests.cpp
src/wire/TerribleCommandBuffer.cpp
src/wire/TerribleCommandBuffer.h
src/wire/Wire.h

This isn't ready to land yet because it causes at least one test to fail:
But @Kangz maybe you can take care of it if this is a problem.

Assert HandleCommands succeeds

---

src/tests/end2end/ComputeCopyStorageBufferTests.cpp

And update comments on several ComputeCopyStorageBufferTests cases.

Partially fix ComputeCopyStorageBufferTests.DISABLED_UnsizedArray

---

src/backend/BindGroupLayout.cpp
src/tests/unittests/validation/BindGroupValidationTests.cpp

Use the binding, not the iterator index.

Fix bind group binding ID validation.

---

src/tests/end2end/RenderPassLoadOpTests.cpp

RenderPassLoadOpTests can pass on Vulkan back-ends now.

Enable RenderPassLoadOpTests on Vulkan back-ends

---

README.md

Github Markdown needs at least two spaces of nesting to add a nesting
level in lists.
PTAL @kainino0x @SenorBlanco

Fix list nesting in README.md

---

dawn.json
examples/ComputeBoids.cpp
examples/CppHelloTriangle.cpp
examples/CubeReflection.cpp
examples/glTFViewer/glTFViewer.cpp
src/dawn_native/BindGroup.cpp
src/dawn_native/BindGroup.h
src/tests/end2end/BlendStateTests.cpp
src/tests/end2end/ComputeCopyStorageBufferTests.cpp
src/tests/end2end/DepthStencilStateTests.cpp
src/tests/end2end/PushConstantTests.cpp
src/tests/end2end/SamplerTests.cpp
src/tests/unittests/validation/BindGroupValidationTests.cpp

BindGroup usage isn't something that's part of WebGPU's sketch.idl and
it might never exist. Remove it to simplify the migration of bindgroup
to descriptor.
PTAL @SenorBlanco @kainino0x

Remove BindGroupBuilder::SetUsage

---

BUILD.gn

Dawn Samples missing correct rpath settings on linux platform in
BUILD.gn. This failed program to find .so like libdawn_native on linux.

Add correct rpath for dawn samples on linux when using gn build

---

infra/config/global/cr-buildbucket.cfg

PTAL @SenorBlanco 
I already landed this on Gerrit to see if it would fix luci-config (it does!) and I'll force push again once this commit is landed on Github.

cr-buildbucket.cfg: Fix missing clang and no_clang mixins

---

infra/config/branch/cq.cfg

A fun bug happened because our CQ config landed both global/ and
branch/ in the same commit. LUCI tries to discover where cq.cfg with
refs.cfg, however the processing of cq.cfg is done before refs.cfg. This
means that when everything was landed at once, the processing of cq.cfg
didn't where to look, and then refs.cfg was processed, but too late.
So this whitespace change will dirty cq.cfg and cause LUCI to discover
it.
PTAL @SenorBlanco

 Fixes for cq.cfg

---

.travis.yml

LLVM 7.0 was branched from ToT because it is going to be released soon.
This means that the repo we use to get clang-format now is LLVM 8.0 so
we update to clang-format-8.
We cannot add the LLVM 7.0 specific repo because it isn't in the Travis
APT source whitelist yet. Opened an issue to add to the whitelist:
https://github.com/travis-ci/apt-source-whitelist/issues/386
Will land this TBR if it passes CI to unblock @Jiawei-Shao.

Update Travis to use clang-format-8 after LLVm release

---

src/include/dawn/dawn_export.h
src/include/dawn_native/dawn_native_export.h
src/include/dawn_wire/dawn_wire_export.h

WIN32 is defined by the SDK, but _WIN32 is defined by the compiler.
Since Dawn doesn't necessarily include <windows.h> everywhere dawn.h is
included, we should use _WIN32 (which will always be defined).

Change WIN32 to _WIN32.

---

infra/config/global/cr-buildbucket.cfg

This will allow testing specific configurations that are on CI
builders when trying to fix them.
Landing this directly as it has been reviewed by tandrii@chromium.org [here](https://dawn-review.googlesource.com/c/dawn/+/1200).

Mirror CI builders in the try pool

---

third_party/BUILD.gn

third_party/BUILD.gn was adding compile flags to suppress failures that
were GCC/Clang specific and caused MSVC to error out. Replace them by
suppression using MSVC's flags.
PTAL @kainino0x @SenorBlanco I verified it passes the MSVC bots in the tryjobs for this CL: https://dawn-review.googlesource.com/c/dawn/+/1220

GN: Fix MSVC compilation

---

dawn.json
examples/CppHelloTriangle.cpp
examples/glTFViewer/glTFViewer.cpp
src/dawn_native/CommandBuffer.cpp
src/dawn_native/CommandBuffer.h
src/dawn_native/Commands.h
src/dawn_native/vulkan/CommandBufferVk.cpp
src/dawn_native/vulkan/TextureVk.cpp
src/tests/DawnTest.cpp
src/tests/end2end/CopyTests.cpp
src/tests/end2end/SamplerTests.cpp
src/tests/unittests/validation/CopyCommandsValidationTests.cpp

This patch implements the creation of a 2D array texture and
copying data between a buffer and a layer of a 2D array texture
on Vulkan back-ends. A new parameter "slice" is added to both
CopyBufferToTexture and CopyTextureToBuffer to specify the
slice of the 2D array texture in this copy operation.
TEST=dawn_end2end_tests

Implement copying between a buffer and a texture 2D array on Vulkan

---

infra/config/global/cr-buildbucket.cfg

There was flakiness on CI because of two things:
- On Windows there is a bot that's only 32bit and our tools are 64bit
so the gn gen step was failing.
- On macOS we require a minimum SDK version of 10.12 (the default in
build/'s GN files) and would get scheduled on macOS 10.9.
TBR @SenorBlanco

cr-buildbucket.cfg: Tighten bot dimensions

---

src/tests/DawnTest.h
src/tests/end2end/BufferTests.cpp
src/tests/end2end/ComputeCopyStorageBufferTests.cpp
src/tests/end2end/CopyTests.cpp
src/tests/end2end/IndexFormatTests.cpp
src/tests/end2end/ScissorTests.cpp

This patch implements a micro DAWN_SKIP_TEST_IF in DawnTest.h which
can be used to skip running a test in dawn_end2end_tests when the
given condition is satisfied.

Implement DAWN_SKIP_TEST_IF for dawn_end2end_tests

---

BUILD.gn
src/dawn_native/CMakeLists.txt
src/dawn_native/d3d12/ComputePipelineD3D12.cpp
src/dawn_native/d3d12/DeviceD3D12.cpp
src/dawn_native/d3d12/DeviceD3D12.h
src/dawn_native/d3d12/PipelineLayoutD3D12.cpp
src/dawn_native/d3d12/PlatformFunctions.cpp
src/dawn_native/d3d12/PlatformFunctions.h
src/dawn_native/d3d12/RenderPipelineD3D12.cpp

Linking against their .lib makes loading Dawn fail on systems that don't
have the DLLs. This happens for example on Windows7 that doesn't have
d3d12.dll. Instead we dynamically load functions pointers from these
DLLs at d3d12::Device startup.
PTAL @SenorBlanco @kainino0x I noticed this issue because of a flake on the Dawn buildbots that were flaking but only when running on the Windows 7 bot.

D3D12: Dynamically load D3D12, DXGI and D3DCompiler

---

src/dawn_native/d3d12/CommandBufferD3D12.cpp
src/dawn_native/d3d12/TextureCopySplitter.cpp
src/dawn_native/d3d12/TextureD3D12.cpp
src/dawn_native/d3d12/TextureD3D12.h
src/dawn_native/metal/CommandBufferMTL.mm
src/dawn_native/metal/TextureMTL.mm
src/dawn_native/opengl/CommandBufferGL.cpp
src/dawn_native/opengl/TextureGL.cpp
src/dawn_native/vulkan/TextureVk.cpp
src/tests/end2end/CopyTests.cpp

This patch implements the creation of 2D array textures and copying
between a buffer and a layer of a 2D array texture on D3D12, Metal
and OpenGL back-ends.
This patch also fixes the barrier in vulkan::Texture::TransitionUsageNow
to make the barrier cover all the slices in a 2D array texture.
TEST=dawn_end2end_tests

Support 2D array texture copying on D3D12, Metal and OpenGL

---

infra/config/global/cr-buildbucket.cfg

This has already been reviewed at https://dawn-review.googlesource.com/c/dawn/+/1340

cr-buildbucket.cfg: Add cache for win_toolchain

---

.gn
DEPS
build_overrides/build.gni

This makes the Linux GN builds use the Chromium copy of binutils and
also makes all platforms use the "custom libcxx" which is libc++.
We do this so that the build doesn't depend on anything from the system
on Linux because our bots are still on trusty with very old libstdc++
and linkers.
This change makes all the bots grren! See https://dawn-review.googlesource.com/c/dawn/+/1320

GN: Use hermetic builds on Linux

---

infra/config/global/cr-buildbucket.cfg

We already had these caches set up and luci-config now complains about
duplicate keys.
Sorry for the churn on this. TBR @kainino0x

Revert "cr-buildbucket.cfg: Add cache for win_toolchain"

---

generator/templates/dawn_native/ValidationUtils.cpp
src/dawn_native/BindGroupLayout.cpp
src/dawn_native/Buffer.cpp
src/dawn_native/CommandBuffer.cpp
src/dawn_native/CommandBufferStateTracker.cpp
src/dawn_native/ComputePipeline.cpp
src/dawn_native/Error.cpp
src/dawn_native/Error.h
src/dawn_native/ErrorData.cpp
src/dawn_native/ErrorData.h
src/dawn_native/PipelineLayout.cpp
src/dawn_native/Sampler.cpp
src/dawn_native/ShaderModule.cpp
src/dawn_native/Texture.cpp
src/dawn_native/d3d12/PlatformFunctions.cpp
src/tests/unittests/ErrorTests.cpp

The error type will help distinguish between validation errors, context
losts and others which should be handled differently.
Take advantage of advantage of this to change DAWN_RETURN_ERROR to
"return DAWN_FOO_ERROR" to have the return be more explicit. Also
removes usage of DAWN_TRY_ASSERT for more explicit checks.

Make Dawn error macro more explicit and have an "error type"
